#!/usr/bin/env python3
"""Regenerate the JSON-LD structured data block in each HTML page.

Run from anywhere:

    python tools/generate_structured_data.py

Every value is read from the page it is written into, so the structured data
cannot drift away from what the page actually says:

    headline / name   the page's <h1>
    description       the page's <meta name="description">
    url / @id         the page's <link rel="canonical">
    image             the page's og:image

Publication dates and categories come from BLOG_POSTS in blog_posts.js, which
is already the single source of truth for the listings.

The block is wrapped in HTML comment markers and inserted before </head>.
Re-running replaces the block in place, so this is safe to run as often as you
like. Any hand-written ld+json on a page is replaced too; edit this script
rather than the pages.

What each page type gets:

    index.html        Person + WebSite
    blog.html         Blog + BreadcrumbList
    blog/<cat>.html   CollectionPage + BreadcrumbList
    blog/posts/*.html BlogPosting + BreadcrumbList

The topic and education pages in the repo root are deliberately left alone.
They have no unambiguous place in a hierarchy, and inventing one would be
worse than describing nothing.
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = "https://ai-yyc.com/"
DEFAULT_IMAGE = BASE + "images/link_preview_AAI_DT_G.png"

START = "<!-- structured data: generated by tools/generate_structured_data.py -->"
END = "<!-- end structured data -->"

# Curated from career_profile.json. Kept here rather than read from that file,
# which belongs to a different project and is not otherwise used by the site.
KNOWS_ABOUT = [
    "Applied AI",
    "AI Governance",
    "Responsible AI",
    "AI Ethics",
    "Digital Transformation",
    "Change Management",
    "AI Adoption and Enablement",
    "Enterprise IT",
]

ALUMNI = ["SAIT", "University of Alberta", "The George Washington University"]

SAME_AS = [
    "https://www.linkedin.com/in/calgaryroy/",
    "https://github.com/comegitit",
]


def read(path):
    return path.read_text(encoding="utf-8")


def clean(text):
    """Strip tags, unescape entities, collapse whitespace."""
    text = re.sub(r"<[^>]+>", "", text)
    return " ".join(html.unescape(text).split())


def find(pattern, text, group=1):
    match = re.search(pattern, text, re.S)
    return match.group(group) if match else None


def canonical_of(text):
    return find(r'rel="canonical"\s+href="([^"]+)"', text)


def description_of(text):
    raw = find(r'name="description"\s+content="([^"]*)"', text)
    if raw is None:
        raw = find(r'name="description"[^>]*?content="([^"]*)"', text)
    return html.unescape(raw).strip() if raw else None


def image_of(text):
    raw = find(r'property="og:image"\s+content="([^"]+)"', text)
    return raw or DEFAULT_IMAGE


def h1_of(text):
    raw = find(r"<h1[^>]*>(.*?)</h1>", text)
    return clean(raw) if raw else None


def author_node():
    return {"@type": "Person", "name": "Roy Aggarwal", "url": BASE}


def breadcrumb(items):
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name, "item": url}
            for i, (name, url) in enumerate(items)
        ],
    }


def load_posts():
    """Return {filename: {date, category}} from BLOG_POSTS, ignoring comments."""
    text = read(ROOT / "blog_posts.js")
    text = re.sub(r"^\s*//.*$", "", text, flags=re.M)
    posts = {}
    for entry in re.findall(r"\{(.*?)\}", text, re.S):
        url = find(r'url\s*:\s*"([^"]+)"', entry)
        date = find(r'date\s*:\s*"([^"]+)"', entry)
        category = find(r'category\s*:\s*"([^"]+)"', entry)
        if url and date:
            posts[url.replace("posts/", "")] = {"date": date, "category": category}
    return posts


def category_pages():
    """Return {category string: filename} by reading each page's own filter."""
    mapping = {}
    for path in sorted((ROOT / "blog").glob("*.html")):
        category = find(r'post\.category\s*===\s*"([^"]+)"', read(path))
        if category:
            mapping[category] = path.name
    return mapping


def graph_for(rel, text, posts, categories):
    """Build the @graph nodes for one page, or None to skip the page."""
    url = canonical_of(text)
    heading = h1_of(text)
    description = description_of(text)

    if rel == "index.html":
        person = {
            "@type": "Person",
            "@id": BASE + "#roy",
            "name": "Roy Aggarwal",
            "alternateName": "AI YYC",
            "url": BASE,
            "email": "roy@ai-yyc.com",
            "jobTitle": "Applied AI | Digital Transformation | AI Governance",
            "description": description,
            "knowsAbout": KNOWS_ABOUT,
            "address": {
                "@type": "PostalAddress",
                "addressLocality": "Calgary",
                "addressRegion": "AB",
                "addressCountry": "CA",
            },
            "alumniOf": [{"@type": "CollegeOrUniversity", "name": n} for n in ALUMNI],
            "sameAs": SAME_AS,
        }
        website = {
            "@type": "WebSite",
            "@id": BASE + "#website",
            "name": "ai-yyc.com",
            "url": BASE,
            "description": description,
            "inLanguage": "en",
            "publisher": {"@id": BASE + "#roy"},
        }
        return [person, website]

    if rel == "blog.html":
        return [
            {
                "@type": "Blog",
                "@id": url,
                "name": heading,
                "description": description,
                "url": url,
                "inLanguage": "en",
                "author": author_node(),
            },
            breadcrumb([("Home", BASE), ("Blog", url)]),
        ]

    if rel.startswith("blog/posts/"):
        meta = posts.get(rel.replace("blog/posts/", ""))
        if not meta:
            return None
        trail = [("Home", BASE), ("Blog", BASE + "blog.html")]
        category_file = categories.get(meta["category"])
        if category_file:
            trail.append((meta["category"], BASE + "blog/" + category_file))
        trail.append((heading, url))
        post = {
            "@type": "BlogPosting",
            "@id": url,
            "mainEntityOfPage": {"@type": "WebPage", "@id": url},
            "url": url,
            "headline": heading,
            "description": description,
            "image": image_of(text),
            "datePublished": meta["date"],
            "inLanguage": "en",
            "author": author_node(),
            "publisher": author_node(),
        }
        if meta["category"]:
            post["articleSection"] = meta["category"]
        return [post, breadcrumb(trail)]

    if rel.startswith("blog/"):
        category = find(r'post\.category\s*===\s*"([^"]+)"', text)
        if not category:
            return None
        return [
            {
                "@type": "CollectionPage",
                "@id": url,
                "name": heading,
                "description": description,
                "url": url,
                "inLanguage": "en",
                "isPartOf": {"@type": "Blog", "@id": BASE + "blog.html"},
            },
            breadcrumb([("Home", BASE), ("Blog", BASE + "blog.html"), (heading, url)]),
        ]

    return None


def render(nodes, indent):
    """Render the marked block, nested one level inside the given indent."""
    pad = indent + "  "
    payload = {"@context": "https://schema.org", "@graph": nodes}
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    body = "\n".join(pad + "  " + line for line in body.splitlines())
    return (
        pad + START + "\n"
        + pad + '<script type="application/ld+json">\n'
        + body + "\n"
        + pad + "</script>\n"
        + pad + END + "\n"
    )


def strip_existing(text):
    # The leading whitespace must be consumed too. Leaving it behind pushes
    # </head> further right on every run, and the block drifts with it.
    text = re.sub(
        r"[ \t]*" + re.escape(START) + r".*?" + re.escape(END) + r"\n?",
        "",
        text,
        flags=re.S,
    )
    text = re.sub(
        r"[ \t]*<script type=\"application/ld\+json\">.*?</script>\n?",
        "",
        text,
        flags=re.S,
    )
    return text


def main():
    posts = load_posts()
    categories = category_pages()
    written, skipped, problems = [], [], []

    for path in sorted(ROOT.rglob("*.html")):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith(".git/"):
            continue

        text = read(path)
        nodes = graph_for(rel, text, posts, categories)
        if nodes is None:
            skipped.append(rel)
            continue

        if not canonical_of(text):
            problems.append("%s has no canonical tag" % rel)
            continue
        if not h1_of(text) and rel != "index.html":
            problems.append("%s has no <h1>" % rel)
            continue
        if not description_of(text):
            problems.append("%s has no meta description" % rel)
            continue

        cleaned = strip_existing(text)
        match = re.search(r"\n([ \t]*)</head>", cleaned)
        if not match:
            problems.append("%s has no </head>" % rel)
            continue

        indent = match.group(1)
        updated = (
            cleaned[: match.start()]
            + "\n"
            + render(nodes, indent)
            + indent
            + "</head>"
            + cleaned[match.end() :]
        )
        if updated != text:
            path.write_text(updated, encoding="utf-8", newline="\n")
        written.append(rel)

    print("Structured data written to %d pages:" % len(written))
    for rel in written:
        print("  " + rel)
    if problems:
        print("\nProblems (these pages were left untouched):")
        for p in problems:
            print("  " + p)
        sys.exit(1)


if __name__ == "__main__":
    main()
